# Minimal Envio config for debugging
name: bsc-trade-indexer
description: Minimal BSCTrade indexer test

# Single contract with one event
contracts:
  - name: TokenLauncher
    abi_file_path: ./abis/TokenLauncher.json
    handler: ./src/Handlers.ts
    events:
      - event: "TokenLaunched(address indexed tokenAddress, address indexed creator, string name, string symbol, uint256 totalSupply)"

# Single network with minimal config
networks:
  - id: 56
    start_block: 57432400
    rpc_config:
      url: https://dark-cosmological-energy.bsc.quiknode.pro/5ac755b984bd05ad070d861f51bd22196cb9d0ab
