# Following exact Envio wildcard example structure
name: bsc-trade-indexer
description: BSCTrade Token Launchpad Indexer

networks:
  - id: 56
    start_block: 57432400
    rpc_config:
      url: https://dark-cosmological-energy.bsc.quiknode.pro/5ac755b984bd05ad070d861f51bd22196cb9d0ab
    contracts:
      - name: TokenLauncher
        abi_file_path: ./abis/TokenLauncher.json
        handler: ./src/EventHandlers.ts
        events:
          - event: "TokenLaunched(address indexed tokenAddress, address indexed creator, string name, string symbol, uint256 totalSupply)"
          - event: "ExternalTokenRegistered(address indexed tokenAddress, address indexed registrar, string name, string symbol)"
